.TH TASKMAN 1 "Март 2025" "v1.0" "Taskman Manual"
.SH NAME
taskman \- simple bash task manager
.SH SYNOPSIS
.B taskman
.RI [command]
.RI [arguments]
.SH DESCRIPTION
Taskman простой менеджер задач написаный на bash
.SH COMMANDS
.TP
.B add
Добавление новой задачи
.TP
.B list
Просмотр всех задач
.TP
.B remove
Удаление задачи по номеру
.SH AUTHOR
Teamofeyy <timarnd06@gmail.com>